CREATE TABLE [dbo].[Utilisateur] (
    [ID]        INT           IDENTITY (1, 1) NOT NULL,
    [NAME]      VARCHAR (255) NULL,
    [FIRSTNAME] VARCHAR (255) NULL,
    [EMAIL]     VARCHAR (255) NULL,
    [PASSWORD]  VARCHAR (255) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO

